Dev
EgorIlinskiy/CardInput pull request #4
Opened 2022-03-28 14:12 UTC by EgorIlinskiy

2022-04-01 12:16 UTC, IlyaRucavitcyn requested changes

2022-04-01 12:16 UTC, IlyaRucavitcyn commented on src/components/translation/index.tsx
> +    else if(language === 'Russian') text = Russian
Think for a second - if this approach is scalable enough? What will happen if we have 5-6-7 languages? Maybe we need another approach?

2022-04-01 12:16 UTC, IlyaRucavitcyn commented on src/store/actions/translation.ts
> +export function SetEnglishLang():LanguageAction{
Is there any reasons you use capital letters for function names?

2022-04-01 12:16 UTC, IlyaRucavitcyn commented on src/types/cardTypes.ts
> +    handleChange:any;
Can we try to avoid `any`?

2022-04-01 12:16 UTC, IlyaRucavitcyn commented on src/types/languageTypes.ts
> +
Note: I saw a lot of places in the code where you have different number of spaces between functions or code snippets

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/InputForms.tsx
> +        cardNumber: cardData !== undefined ? cardData.cardNumber : '',
Non actual file

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/InputForms.tsx
> +        initialValues:initialValues,
Refactor it

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/InputForms.tsx
> +        validationSchema:yup.object({
Moved schema to separate file

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/InputForms.tsx
> +                 >Pay now</button>
Non actual files

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/InputForms.tsx
> +                    onClick={()=>{SwitchMode()}}
There is no reason. Changed func names

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/SavedCards.tsx
> +            console.log(card.cardId)
Non actual file

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/options/optionsForSelect.ts
> +function generateYears():object[]{
This two functions need to generate options for select components. yearOptions generate object with 10+ years options, month generate object with 12 month

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/store/actions/card.ts
> +export function AddNewCard(data:IFormValues):CardActions{
Non actual file. Refactor also this.

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/store/reducers/cardReducers.ts
> +const initialState:CardStateType = {
Even if we need some initial state?

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/store/reducers/cardReducers.ts
> +            console.log(newCards)
Delete it

2022-04-03 17:06 UTC, EgorIlinskiy commented on src/components/card/CustomSelect.tsx
> +     const customStyles: StylesConfig<any> = {
Refactor to Styled, but now onChange handler have any type, and i cant find what type is it

2022-04-03 17:07 UTC, EgorIlinskiy commented on src/components/card/PaymentForm.tsx
> +        validationSchema:yup.object({
Moved schema to separate file

2022-04-03 17:07 UTC, EgorIlinskiy commented on src/components/card/PaymentForm.tsx
> +                .typeError('Card number must contains only numbers!')
Even if we not show it to users? i used only red color, if error has occurred

2022-04-03 17:07 UTC, EgorIlinskiy commented on src/components/card/PaymentForm.tsx
> +                            defaultMessage={'3 or 4 digits code'}
Default message? But it used only when id cannot be found

2022-04-03 17:07 UTC, EgorIlinskiy commented on src/store/actions/translation.ts
> +export function SetEnglishLang():LanguageAction{
Nope. Renamed it

2022-04-03 17:07 UTC, EgorIlinskiy commented on src/types/cardTypes.ts
> +    handleChange:any;
HandleChange we can. But for options and onblur even the official documentation writes unknown type.

2022-04-03 17:13 UTC, EgorIlinskiy commented on src/components/card/CustomSelect.tsx
> +     const customStyles: StylesConfig<any> = {
> Refactor to Styled, but now onChange handler have any type, and i cant find what type is it

Oh no... custom styles need to be in props. If we put it at styled, styles do not apply

2022-04-03 17:22 UTC, EgorIlinskiy commented on src/components/translation/index.tsx
> +   if(language === 'English') text = English
Refactor languages types to enum

2022-04-03 17:23 UTC, EgorIlinskiy commented on src/components/translation/index.tsx
> +    else if(language === 'Russian') text = Russian
If we rewrite it to switch cases, will it help us? 
Or we need some another way

2022-04-03 17:23 UTC, EgorIlinskiy commented on src/types/languageTypes.ts
> +
Got it.

2022-04-03 18:21 UTC, EgorIlinskiy commented on src/components/card/SavedCards.tsx
> +                        <VisaLogo/>
We have that mechanism. Added to form visa and mastercard logo.

2022-04-04 13:06 UTC, IlyaRucavitcyn approved these changes

2022-04-04 13:10 UTC, merged